name: CI/CD Pipeline

on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.425'

    - name: Restore dependencies
      run: dotnet restore ./AutoMoreira.sln

    - name: Build the project
      run: dotnet build ./AutoMoreira.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./AutoMoreira.sln --no-restore --verbosity normal

  docker:
    needs: build
    runs-on: ubuntu-latest

    - name: Build the Docker image
      working-directory: ./
      run: docker build . -t prafaelmsantos/automoreiraapi:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push docker-hub-username/container-name
