name: CI/CD Pipeline

on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.425'

    - name: Restore dependencies
      run: dotnet restore ./AutoMoreira.sln

    - name: Build the project
      run: dotnet build ./AutoMoreira.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./AutoMoreira.sln --no-restore --verbosity normal

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/automoreiraapi:latest
